// ReSharper disable CppClangTidyClangDiagnosticIncompatibleFunctionPointerTypesStrict
#include "PvzAnimation.h"

#include <stdlib.h>
#include <string.h>

#include "FileIO.h"

void PvzAnimation_Create(PvzAnimation* self)
{
    static PvzAnimation_VTable pvz_animation_vtable = {
        .Create = PvzAnimation_Create,
        .Destroy = PvzAnimation_Destroy,
        .New = PvzAnimation_New,
        .Delete = PvzAnimation_Delete,

        .Init = PvzAnimation_Init,
        .OpenOutputFiles = PvzAnimation_OpenOutputFiles,
        .FreeFiles = PvzAnimation_FreeFiles,

        .PrintExtResourceToFile = PvzAnimation_PrintExtResourceToFile,
        .PrintSetAnimToFile = PvzAnimation_PrintSetAnimToFile,
        .PrintTracksToFile = PvzAnimation_PrintTracksToFile,
        .PrintAddNodeToFile = PvzAnimation_PrintAddNodeToFile
    };
    self->vptr = &pvz_animation_vtable;
    memset(self->anim_name, 0, sizeof(self->anim_name));
    self->start_frame_time = 0;
    self->end_frame_time = 0;
    self->all_tracks_num = 0;
    if ((self->tracks = PvzTracks_New()) == NULL) return;
    self->current_frame_time_num = 0;
    self->current_tracks_num = 0;

    memset(self->output_file_extension, 0, sizeof(self->output_file_extension));
    memset(self->str_output, 0, sizeof(self->str_output));
    memset(self->str_first_output_ext, 0, sizeof(self->str_first_output_ext));
    memset(self->str_second_output_anim, 0, sizeof(self->str_second_output_anim));
    memset(self->str_third_output_track, 0, sizeof(self->str_third_output_track));
    memset(self->str_forth_output_node, 0, sizeof(self->str_forth_output_node));

    self->ofp_output = NULL;
    self->ofp_first_ext = NULL;
    self->ofp_second_anim = NULL;
    self->ofp_third_track = NULL;
    self->ofp_forth_node = NULL;

    memset(self->texture_filename, 0, sizeof(self->texture_filename));
    self->texture_filename_times = 0;
    memset(self->track_name, 0, sizeof(self->track_name));
    memset(self->res_file_name, 0, sizeof(self->res_file_name));
}

void PvzAnimation_Destroy(const PvzAnimation* self)
{
    if (self == NULL) return;
    self->tracks->vptr->Delete(self->tracks);
}

PvzAnimation* PvzAnimation_New()
{
    PvzAnimation* self = (PvzAnimation*)malloc(sizeof(PvzAnimation));
    if (!self)
        return NULL;
    PvzAnimation_Create(self);
    return self;
}

void PvzAnimation_Delete(PvzAnimation* self)
{
    if (self == NULL) return;
    PvzAnimation_Destroy(self);
    free(self);
}

void PvzAnimation_Init(PvzAnimation* self, const char* anim_name, const char* output_file_extension, const R2GAStartParam* start_param)
{
    snprintf(self->anim_name, NAME_LENGTH, "%s", anim_name);
    PvzTracks_Init(self->tracks, start_param);
    snprintf(self->output_file_extension, EXT_LENGTH, "%s", output_file_extension);
}

// 释放PVZAnimation
void PvzAnimation_FreeFiles(const PvzAnimation* self, const bool is_remove_output_files)
{
    if (self == NULL) return;
    if (strcmp(self->anim_name, "null") != 0)
    {
        //printf("debug: PvzAnimation_FreeFiles--%s\n", self->anim_name);
    }

    // 关闭输出文件
    FileClose(self->ofp_output);
    FileClose(self->ofp_first_ext);
    FileClose(self->ofp_second_anim);
    FileClose(self->ofp_third_track);
    FileClose(self->ofp_forth_node);
    // 释放PVZTracks

    self->tracks->vptr->Delete(self->tracks);

    // 删除输出文件
    if (is_remove_output_files)
    {
        remove(self->str_output);
    }
    remove(self->str_first_output_ext);
    remove(self->str_second_output_anim);
    remove(self->str_third_output_track);
    remove(self->str_forth_output_node);
}

void PvzAnimation_PrintExtResourceToFile(const PvzAnimation* self, PvzAnimation* anims[], const int anims_size, const R2GAStartParam* const start_param)
{
    if (self == NULL) return;

    FILE* const p_file = self->ofp_first_ext;

    // 写入资源引用部分
    fprintf_s(p_file, "; Generated by PVZ_reanim2godot_animation v%s\n\n", VERSION);
    if (start_param->blendModeTrackEnabled)
    {
        fprintf_s(p_file, "[ext_resource type=\"Shader\" path=\"res://normal.gdshader\" id=\"normal_shader\"]\n");
        fprintf_s(p_file, "[ext_resource type=\"Shader\" path=\"res://add.gdshader\" id=\"add_shader\"]\n");
    }
    for (int i = 0; i < self->texture_filename_times; i++)
    {
        fprintf_s(p_file, "[ext_resource type=\"Texture2D\" path=\"%s%s\" id=\"%d_fuck\"]\n", start_param->resourceGodotPath, self->texture_filename[i], i);
    }
    fprintf_s(p_file, "\n");
    const bool is_ext_anim_enabled = start_param->outputMode != OutputMode_TscnByAnim;
    if (strcmp(self->output_file_extension, "tscn"/*MODE_TSCN_STR*/) == 0 && is_ext_anim_enabled)
    {
        if (self->anim_index != 0) printf("animation index: %d\n", self->anim_index);
        for (int i = 1; i <= anims_size; i++)
        {
            if (i == self->anim_index)
            {
                continue;
            }
            fprintf_s(p_file, "[ext_resource type=\"Animation\" path=\"%s%s.tres\" id=\"%d_anim\"]\n", start_param->animOutputGodotPath, anims[i]->res_file_name, i);
        }
        fprintf_s(p_file, "\n");
    }

    if (start_param->blendModeTrackEnabled)
    {
        fprintf_s(p_file,
            "[sub_resource type=\"ShaderMaterial\" id=\"ShaderMaterial_normal\"]\n"
            "shader = ExtResource(\"normal_shader\")\n"
            "\n"
            "[sub_resource type=\"ShaderMaterial\" id=\"ShaderMaterial_add\"]\n"
            "shader = ExtResource(\"add_shader\")\n"
            "\n");
    }
    fflush(p_file);
}

void PvzAnimation_PrintSetAnimToFile(const PvzAnimation* self)
{
    FILE* const p_file = self->ofp_second_anim;
    fprintf_s(p_file, "; Generated by PVZ_reanim2godot_animation v%s\n\n", VERSION);
    if (strcmp(self->output_file_extension, "tres"/*MODE_ANIM_TRES_STR*/) == 0)
    {
        fprintf_s(p_file, "[resource]\nresource_name = \"%s\"\n", self->res_file_name);
    }
    else // strcmp(self->output_file_extension, tscn MODE_TSCN_BY_ANIM_STR) == 0
    {
        fprintf_s(p_file, "[sub_resource type=\"Animation\" id=\"Animation_fuck\"]\n");
    }
    fprintf_s(p_file, "length = %.6Lf\n", (float)(self->current_frame_time_num - 1) * (1.0 / FPS));
    fprintf_s(p_file, "step = %.6Lf\n", 1.0 / FPS);
    fflush(p_file);
}

void PvzAnimation_PrintTracksToFile(const PvzAnimation* self, FILE* p_file, const R2GAStartParam* start_param)
{
    //FILE* const p_file = self->ofp_third_track;
    const PvzTracks* const tracks = self->tracks;
    if (start_param->visibleTrackEnabled)    tracks->vis->vptr->PrintToFile(tracks->vis, p_file);
    tracks->pos->vptr->PrintToFile(tracks->pos, p_file);
    tracks->rot->vptr->PrintToFile(tracks->rot, p_file);
    tracks->scale->vptr->PrintToFile(tracks->scale, p_file);
    tracks->skew->vptr->PrintToFile(tracks->skew, p_file);
    if (start_param->textureTrackEnabled)    tracks->texture->vptr->PrintToFile(tracks->texture, p_file);
    if (start_param->alphaTrackEnabled)      tracks->alpha->vptr->PrintToFile(tracks->alpha, p_file);

    fflush(p_file);
}

void PvzAnimation_PrintAddNodeToFile(const PvzAnimation* self, const int anim_num, const R2GAStartParam* start_param)
{
    FILE* const p_file = self->ofp_forth_node;
    fprintf_s(p_file, "; Generated by PVZ_reanim2godot_animation v%s\n\n", VERSION);

// 添加 AnimationLibrary 资源，一个动画资源对应一个动画库
    // 添加总动画节点
    fprintf_s(p_file, "[sub_resource type=\"AnimationLibrary\" id=\"AnimationLibrary_fuck\"]\n"
        "_data = {\n"
        "\"ALL_ANIMS\": SubResource(\"Animation_fuck\")\n"
        "}\n\n");
    // 添加每个分动画的 Library 资源，动画资源由 PrintExtResourceToFile 函数导入
    for (int i = 1; i <= anim_num && start_param->outputMode != OutputMode_TscnByAnim; i++)
    {
        fprintf_s(p_file, "[sub_resource type=\"AnimationLibrary\" id=\"AnimationLibrary_%s\"]\n", self->res_file_name);
        fprintf_s(p_file, "_data = {\n");
        fprintf_s(p_file, "&\"%s\": ExtResource(\"%d_anim\")\n", self->res_file_name, i);
        fprintf_s(p_file, "}\n");
    }
// 添加部件节点
    // 添加根节点 Node2D
    fprintf_s(p_file, "[node name=\"Node2D\" type=\"Node2D\"]\n\n");
    // 添加每个分动画的 Sprite2D 节点，节点名与分动画名（轨道名）相同
    for (int i = 0; i < self->current_tracks_num; i++)
    {
        fprintf_s(p_file, "[node name=\"%s\" type=\"Sprite2D\" parent=\".\"]\n", self->track_name[i]);
        fprintf_s(p_file, "centered = false\n\n");
    }
// 添加 AnimationPlayer 节点，用于播放动画
    // 添加总动画播放器节点
    fprintf_s(p_file,
        "[node name=\"AnimLib\" type=\"AnimationPlayer\" parent=\".\"]\n"
        "libraries = {\n"
        "\"\": SubResource(\"AnimationLibrary_fuck\")\n"
        "}\n\n");
    // 添加每个分动画的 AnimationPlayer 节点
    for (int i = 1; i <= anim_num && start_param->outputMode != OutputMode_TscnByAnim; i++)
    {
        fprintf_s(p_file,
            "[node name=\"Anim_%s\" type=\"AnimationPlayer\" parent=\".\"]\n"
            "libraries = {\n"
            "\"\": SubResource(\"AnimationLibrary_%s\")\n"
            "}\n\n",
            self->res_file_name, self->res_file_name);
    }
    fflush(p_file);
}

void PvzAnimation_OpenOutputFiles(PvzAnimation* self, const char* output_file_path)
{
    sprintf_s(self->str_output, NAME_LENGTH, "%s%s.%s", output_file_path, self->res_file_name, self->output_file_extension);
    printf("debug: OutputFiles:str_output--%s\n", self->str_output);
    // 将argv[2]和 "first" 写入str_first_output_ext
    sprintf_s(self->str_first_output_ext, NAME_LENGTH, "%s%s_first_ext.jiema", output_file_path, self->res_file_name);
    // 将argv[2]和 "second" 写入str_second_output_anim
    sprintf_s(self->str_second_output_anim, NAME_LENGTH, "%s%s_second_anim.jiema", output_file_path, self->res_file_name);
    // 将argv[2]和 "third" 写入str_third_output_track
    sprintf_s(self->str_third_output_track, NAME_LENGTH, "%s%s_third_track.jiema", output_file_path, self->res_file_name);
    // 将argv[2]和 "forth" 写入str_forth_output_node
    sprintf_s(self->str_forth_output_node, NAME_LENGTH, "%s%s_forth_node.jiema", output_file_path, self->res_file_name);

    // 打开输出文件
    FileOpen(&(self->ofp_output), self->str_output, "w", ErrorCode_CannotOpenOutputFile);
    // 打开ext输出文件
    FileOpen(&(self->ofp_first_ext), self->str_first_output_ext, "w+", ErrorCode_CannotOpenExtOutputFile);
    // 打开anim输出文件
    FileOpen(&(self->ofp_second_anim), self->str_second_output_anim, "w+", ErrorCode_CannotOpenAnimOutputFile);
    // 打开track输出文件
    FileOpen(&(self->ofp_third_track), self->str_third_output_track, "w+", ErrorCode_CannotOpenTrackOutputFile);
    // 打开node输出文件
    FileOpen(&(self->ofp_forth_node), self->str_forth_output_node, "w+", ErrorCode_CannotOpenNodeOutputFile);
}