#include "ResourceFile.h"

#include <stdlib.h>
#include <string.h>

#include "FileIO.h"

void _ResourceFile_Create(ResourceFile* self, PvzAnimation* p_anim)
{
    self->p_anim = p_anim;
    self->p_file = NULL;
    memset(self->name, 0, sizeof(self->name));
}

void _ResourceFile_Destroy(ResourceFile* self)
{
    if (self == NULL) return;
    if (self->p_file) FileClose(self->p_file);
    //if (self->p_anim) self->p_anim->vptr->Destroy(self->p_anim);
    self->vptr = NULL;
    self->p_file = NULL;
    self->p_anim = NULL;
}

void ResourceFile_PrintTracks(const ResourceFile* self, const R2GAStartParam* start_param)
{
    self->p_anim->vptr->PrintTracksToFile(self->p_anim, self->p_file, start_param);
}

///////////////////////////
/////      Tres       /////
///////////////////////////

void Tres_Create(Tres* self, PvzAnimation* p_anim)
{
    static _ResourceFile_VTable tres_vtable = {
        .Destroy = Tres_Destroy,
        .Delete = Tres_Delete,
        .OpenOutputFile = Tres_OpenOutputFile,
        .PrintExtResource = Tres_PrintExtResource,
        .PrintSetAnim = Tres_PrintSetAnim,
        .PrintTracks = ResourceFile_PrintTracks
    };
    _ResourceFile_Create((ResourceFile*)self, p_anim);
    self->vptr = (void*)&tres_vtable;
}

void Tres_Destroy(Tres* self)
{
    if (self == NULL) return;
    _ResourceFile_Destroy((ResourceFile*)self);
}

Tres* Tres_New(PvzAnimation* p_anim)
{
    Tres* self = (Tres*)malloc(sizeof(Tres));
    if (!self)    return NULL;
    Tres_Create(self, p_anim);
    return self;
}

void Tres_Delete(Tres* self)
{
    if (!self) return;
    Tres_Destroy(self);
    free(self);
}

void Tres_OpenOutputFile(Tres* self, const char* output_file_path)
{
    sprintf_s(self->name, NAME_LENGTH, "%s%s.tres", output_file_path, *self->name ? self->name : self->p_anim->res_file_name);
    printf("debug: OutputFiles:name--%s\n", self->name);
    FileOpen(&self->p_file, self->name, "w", ErrorCode_CannotOpenOutputFile);
}

void Tres_PrintExtResource(const Tres* self, const R2GAStartParam* const start_param)
{
    if (self == NULL) return;

    // 写入资源引用部分
    fprintf_s(self->p_file, "; Generated by PVZ_reanim2godot_animation v%s\n\n", VERSION);
    fprintf_s(self->p_file, "[gd_resource type=\"Animation\"]\n");
    if (start_param->blendModeTrackEnabled)
    {
        fprintf_s(self->p_file, "[ext_resource type=\"Shader\" path=\"res://normal.gdshader\" id=\"normal_shader\"]\n");
        fprintf_s(self->p_file, "[ext_resource type=\"Shader\" path=\"res://add.gdshader\" id=\"add_shader\"]\n");
    }
    for (int i = 0; i < self->p_anim->texture_filename_times; i++)
    {
        fprintf_s(self->p_file, "[ext_resource type=\"Texture2D\" path=\"%s%s\" id=\"%d_fuck\"]\n", start_param->resourceGodotPath, self->p_anim->texture_filename[i], i);
    }
    fprintf_s(self->p_file, "\n");

    if (start_param->blendModeTrackEnabled)
    {
        fprintf_s(self->p_file,
            "[sub_resource type=\"ShaderMaterial\" id=\"ShaderMaterial_normal\"]\n"
            "shader = ExtResource(\"normal_shader\")\n"
            "\n"
            "[sub_resource type=\"ShaderMaterial\" id=\"ShaderMaterial_add\"]\n"
            "shader = ExtResource(\"add_shader\")\n"
            "\n");
    }
    fflush(self->p_file);
}

void Tres_PrintSetAnim(const Tres* self, const int fps)
{
    fprintf_s(self->p_file, "; Generated by PVZ_reanim2godot_animation v%s\n\n", VERSION);
    fprintf_s(self->p_file, "[resource]\nresource_name = \"%s\"\n", self->p_anim->res_file_name);
    //fprintf_s(self->p_file, "[sub_resource type=\"Animation\" id=\"Animation_fuck\"]\n");
    fprintf_s(self->p_file, "length = %.6Lf\n", (float)(self->p_anim->current_frame_time_num - 1) * (1.0 / fps));
    fprintf_s(self->p_file, "step = %.6Lf\n", 1.0 / fps);
    fflush(self->p_file);
}

///////////////////////////
/////      Tscn       /////
///////////////////////////

void Tscn_Create(Tscn* self, PvzAnimation* p_anim, PvzAnimation* anims[], const int anims_num)
{
    static _Tscn_VTable tscn_vtable = {
        .Destroy = Tscn_Destroy,
        .Delete = Tscn_Delete,
        .OpenOutputFile = Tscn_OpenOutputFile,
        .PrintExtResource = Tscn_PrintExtResource,
        .PrintSetAnim = Tscn_PrintSetAnim,
        .PrintTracks = ResourceFile_PrintTracks,
        .PrintAddNode = Tscn_PrintAddNode
    };
    _ResourceFile_Create((ResourceFile*)self, p_anim);
    self->vptr = (void*)&tscn_vtable;
    self->anims = anims;
    self->anims_num = anims_num;
}

void Tscn_Destroy(Tscn* self)
{
    if (self == NULL) return;
    _ResourceFile_Destroy((ResourceFile*)self);
    self->anims = NULL;
    self->anims_num = 0;
}

Tscn* Tscn_New(PvzAnimation* p_anim, PvzAnimation* anims[], const int anims_num)
{
    Tscn* self = (Tscn*)malloc(sizeof(Tscn));
    if (!self)    return NULL;
    Tscn_Create(self, p_anim, anims, anims_num);
    return self;
}

void Tscn_Delete(Tscn* self)
{
    if (!self) return;
    Tscn_Destroy(self);
    free(self);
}

void Tscn_OpenOutputFile(Tscn* self, const char* output_file_path)
{
    sprintf_s(self->name, NAME_LENGTH, "%s%s.tscn", output_file_path, *self->name ? self->name : self->p_anim->res_file_name);
    printf("debug: OutputFiles:name--%s\n", self->name);
    FileOpen(&self->p_file, self->name, "w", ErrorCode_CannotOpenOutputFile);
}

void Tscn_PrintExtResource(const Tscn* self, const R2GAStartParam* start_param)
{
    if (self == NULL) return;

    // 写入资源引用部分
    fprintf_s(self->p_file, "; Generated by PVZ_reanim2godot_animation v%s\n\n", VERSION);
    fprintf_s(self->p_file, "[gd_scene]\n\n");
    if (start_param->blendModeTrackEnabled)
    {
        fprintf_s(self->p_file,
            "[ext_resource type=\"Shader\" path=\"res://normal.gdshader\" id=\"normal_shader\"]\n"
            "[ext_resource type=\"Shader\" path=\"res://add.gdshader\" id=\"add_shader\"]\n");
    }
    for (int i = 0; i < self->p_anim->texture_filename_times; i++)
    {
        fprintf_s(self->p_file, "[ext_resource type=\"Texture2D\" path=\"%s%s\" id=\"%d_fuck\"]\n", start_param->resourceGodotPath, self->p_anim->texture_filename[i], i);
    }
    fprintf_s(self->p_file, "\n");
    const bool is_ext_anim_enabled = start_param->outputMode != OutputMode_TscnByAnim;
    if (is_ext_anim_enabled)
    {
        if (self->p_anim->anim_index != 0) printf("animation index: %d\n", self->p_anim->anim_index);
        for (int i = 1; i <= self->anims_num; i++)
        {
            if (i == self->p_anim->anim_index)    continue;
            fprintf_s(self->p_file, "[ext_resource type=\"Animation\" path=\"%s%s.tres\" id=\"%d_anim\"]\n", start_param->animOutputGodotPath, self->anims[i]->res_file_name, i);
        }
        fprintf_s(self->p_file, "\n");
    }

    if (start_param->blendModeTrackEnabled)
    {
        fprintf_s(self->p_file,
            "[sub_resource type=\"ShaderMaterial\" id=\"ShaderMaterial_normal\"]\n"
            "shader = ExtResource(\"normal_shader\")\n"
            "\n"
            "[sub_resource type=\"ShaderMaterial\" id=\"ShaderMaterial_add\"]\n"
            "shader = ExtResource(\"add_shader\")\n"
            "\n");
    }
    fflush(self->p_file);
}

void Tscn_PrintSetAnim(const Tscn* self, const int fps)
{
    fprintf_s(self->p_file, "; Generated by PVZ_reanim2godot_animation v%s\n\n", VERSION);
    fprintf_s(self->p_file, "[sub_resource type=\"Animation\" id=\"Animation_fuck\"]\n");
    fprintf_s(self->p_file, "length = %.6Lf\n", (float)(self->p_anim->current_frame_time_num - 1) * (1.0 / fps));
    fprintf_s(self->p_file, "step = %.6Lf\n", 1.0 / fps);
    fflush(self->p_file);
}

void Tscn_PrintAddNode(const Tscn* self, const R2GAStartParam* start_param)
{
    fprintf_s(self->p_file, "; Generated by PVZ_reanim2godot_animation v%s\n\n", VERSION);

    // 添加 AnimationLibrary 资源，一个动画资源对应一个动画库
    // 添加总动画节点
    fprintf_s(self->p_file, "[sub_resource type=\"AnimationLibrary\" id=\"AnimationLibrary_fuck\"]\n"
        "_data = {\n"
        "\"ALL_ANIMS\": SubResource(\"Animation_fuck\")\n"
        "}\n\n");
// 添加每个分动画的 Library 资源，动画资源由 PrintExtResourceToFile 函数导入
    if (start_param->outputMode != OutputMode_TscnByAnim)
        for (int i = 1; i <= self->anims_num; i++)
        {
            fprintf_s(self->p_file, "[sub_resource type=\"AnimationLibrary\" id=\"AnimationLibrary_%s\"]\n", self->anims[i]->res_file_name);
            fprintf_s(self->p_file, "_data = {\n");
            fprintf_s(self->p_file, "&\"%s\": ExtResource(\"%d_anim\")\n", self->anims[i]->res_file_name, i);
            fprintf_s(self->p_file, "}\n");
        }
        // 添加部件节点
        // 添加根节点 Node2D
    fprintf_s(self->p_file, "[node name=\"Node2D\" type=\"Node2D\"]\n\n");
    // 添加每个分动画的 Sprite2D 节点，节点名与分动画名（轨道名）相同
    for (int i = 0; i < self->p_anim->current_tracks_num; i++)
    {
        fprintf_s(self->p_file, "[node name=\"%s\" type=\"Sprite2D\" parent=\".\"]\n", self->p_anim->track_name[i]);
        fprintf_s(self->p_file, "centered = false\n\n");
    }
    // 添加 AnimationPlayer 节点，用于播放动画
    // 添加总动画播放器节点
    fprintf_s(self->p_file,
        "[node name=\"AnimLib\" type=\"AnimationPlayer\" parent=\".\"]\n"
        "libraries = {\n"
        "\"\": SubResource(\"AnimationLibrary_fuck\")\n"
        "}\n\n");
// 添加每个分动画的 AnimationPlayer 节点
    if (start_param->outputMode != OutputMode_TscnByAnim)
        for (int i = 1; i <= self->anims_num; i++)
        {
            fprintf_s(self->p_file,
                "[node name=\"Anim_%s\" type=\"AnimationPlayer\" parent=\".\"]\n"
                "libraries = {\n"
                "\"\": SubResource(\"AnimationLibrary_%s\")\n"
                "}\n\n",
                self->anims[i]->res_file_name, self->anims[i]->res_file_name);
        }
    fflush(self->p_file);
}