#include "resource.h"

#include <cstdio>

#include "version.h"

namespace r2ga {
namespace {

/// 混合模式开启时，两个 shader 的 ext_resource 声明（.tres 与 .tscn 共用）。
void print_shader_ext_resources(OutFile& out)
{
    out.write("[ext_resource type=\"Shader\" path=\"res://normal.gdshader\" id=\"normal_shader\"]\n"
              "[ext_resource type=\"Shader\" path=\"res://add.gdshader\" id=\"add_shader\"]\n");
}

/// 混合模式开启时，两个 ShaderMaterial 的 sub_resource 声明（.tres 与 .tscn 共用）。
void print_shader_materials(OutFile& out)
{
    out.write("[sub_resource type=\"ShaderMaterial\" id=\"ShaderMaterial_normal\"]\n"
              "shader = ExtResource(\"normal_shader\")\n"
              "\n"
              "[sub_resource type=\"ShaderMaterial\" id=\"ShaderMaterial_add\"]\n"
              "shader = ExtResource(\"add_shader\")\n"
              "\n");
}

/// 每个用到的贴图一条 ext_resource。
/// 注意 id 里的 "_fuck" 是原实现的字面量，不是笔误，改了会改变输出。
void print_texture_ext_resources(OutFile& out, const Params& params, const PvzAnimation& anim)
{
    for (std::size_t i = 0; i < anim.texture_filename.size(); ++i)
    {
        out.print("[ext_resource type=\"Texture2D\" path=\"{}{}\" id=\"{}_fuck\"]\n",
                  params.resourceGodotPath, anim.texture_filename[i], i);
    }
}

/// `length = %.6Lf` 的实参，逐字保留原实现的类型：
/// `(float)(帧数 - 1) * (1.0 / fps)` —— 先转 float，再与 double 相乘。
f64 anim_length(const PvzAnimation& anim, int fps)
{
    return static_cast<float>(anim.current_frame_time_num - 1) * (1.0 / fps);
}

void write_length_step(OutFile& out, const PvzAnimation& anim, int fps)
{
    out.write("length = ");
    out.print("{:.6f}", anim_length(anim, fps));
    out.write("\n");

    out.write("step = ");
    out.print("{:.6f}", 1.0 / fps);
    out.write("\n");
}

}  // namespace

void ResourceFile::open_output_file(const std::string& output_file_path)
{
    // 原实现：sprintf_s(self->name, NAME_LENGTH, "%s%s%s", path,
    //                   *self->name ? self->name : res_file_name, ext);
    // name_ 初始为空，所以第一次进来取 res_file_name。
    name_ = clamp_name(output_file_path + (name_.empty() ? p_anim_->res_file_name : name_)
                       + extension());

    std::printf("debug: OutputFiles:name--%s\n", name_.c_str());
    out_.open(name_, ErrorCode_CannotOpenOutputFile);
}

// ------------------------------------------------------------------- Tres

void Tres::print_ext_resource(const Params& params)
{
    out_.print("; Generated by PVZ_reanim2godot_animation v{}\n\n", VERSION);
    out_.write("[gd_resource type=\"Animation\"]\n");

    if (params.blend_mode())
        print_shader_ext_resources(out_);

    print_texture_ext_resources(out_, params, *p_anim_);
    out_.write("\n");

    if (params.blend_mode())
        print_shader_materials(out_);

    out_.flush();
}

void Tres::print_set_anim(int fps)
{
    out_.print("; Generated by PVZ_reanim2godot_animation v{}\n\n", VERSION);
    out_.print("[resource]\nresource_name = \"{}\"\n", p_anim_->res_file_name);
    write_length_step(out_, *p_anim_, fps);
    out_.flush();
}

// ------------------------------------------------------------------- Tscn

void Tscn::print_ext_resource(const Params& params)
{
    out_.print("; Generated by PVZ_reanim2godot_animation v{}\n\n", VERSION);
    out_.write("[gd_scene]\n\n");

    if (params.blend_mode())
        print_shader_ext_resources(out_);

    print_texture_ext_resources(out_, params, *p_anim_);
    out_.write("\n");

    const bool is_ext_anim_enabled = params.output_mode() != OutputMode::TscnByAnim;
    if (is_ext_anim_enabled)
    {
        // 原实现：if (self->p_anim->anim_index != 0) printf("animation index: %d\n", ...)
        // p_anim 恒为 anims[0]，其 anim_index 恒为 0，所以这一行永远不打印。
        if (p_anim_->anim_index != 0)
            std::printf("animation index: %d\n", p_anim_->anim_index);

        // anims_ 的长度是 anim_nums + 1，所以 i 取 1..anim_nums
        // （与原实现的 i <= anims_num 一致）
        for (std::size_t i = 1; i < anims_.size(); ++i)
        {
            // i 从 1 起，而 p_anim_->anim_index 恒为 0，所以这个 continue 永不触发。
            if (static_cast<int>(i) == p_anim_->anim_index)
                continue;
            out_.print("[ext_resource type=\"Animation\" path=\"{}{}.tres\" id=\"{}_anim\"]\n",
                       params.animOutputGodotPath, anims_[i]->res_file_name, i);
        }
        out_.write("\n");
    }

    if (params.blend_mode())
        print_shader_materials(out_);

    out_.flush();
}

void Tscn::print_set_anim(int fps)
{
    out_.print("; Generated by PVZ_reanim2godot_animation v{}\n\n", VERSION);
    out_.write("[sub_resource type=\"Animation\" id=\"Animation_fuck\"]\n");
    write_length_step(out_, *p_anim_, fps);
    out_.flush();
}

void Tscn::print_add_node(const Params& params)
{
    out_.print("; Generated by PVZ_reanim2godot_animation v{}\n\n", VERSION);

    out_.write("[sub_resource type=\"AnimationLibrary\" id=\"AnimationLibrary_fuck\"]\n"
               "_data = {\n"
               "\"ALL_ANIMS\": SubResource(\"Animation_fuck\")\n"
               "}\n\n");

    const bool is_ext_anim_enabled = params.output_mode() != OutputMode::TscnByAnim;

    if (is_ext_anim_enabled)
    {
        for (std::size_t i = 1; i < anims_.size(); ++i)
        {
            out_.print("[sub_resource type=\"AnimationLibrary\" id=\"AnimationLibrary_{}\"]\n",
                       anims_[i]->res_file_name);
            out_.write("_data = {\n");
            out_.print("&\"{}\": ExtResource(\"{}_anim\")\n", anims_[i]->res_file_name, i);
            out_.write("}\n");
        }
    }

    // 根节点：未指定名称时回退到资源名
    out_.print("[node name=\"{}\" type=\"{}\"]\n\n",
               params.root_node_name_is_set() ? params.root_node_name() : p_anim_->res_file_name,
               params.root_node_type());

    for (int i = 0; i < p_anim_->current_tracks_num; ++i)
    {
        out_.print("[node name=\"{}\" type=\"Sprite2D\" parent=\".\"]\n",
                   p_anim_->track_name[static_cast<std::size_t>(i)]);
        out_.write("centered = false\n\n");
    }

    out_.write("[node name=\"AnimLib\" type=\"AnimationPlayer\" parent=\".\"]\n"
               "libraries = {\n"
               "\"\": SubResource(\"AnimationLibrary_fuck\")\n"
               "}\n\n");

    if (is_ext_anim_enabled)
    {
        for (std::size_t i = 1; i < anims_.size(); ++i)
        {
            out_.print("[node name=\"Anim_{}\" type=\"AnimationPlayer\" parent=\".\"]\n"
                       "libraries = {{\n"
                       "\"\": SubResource(\"AnimationLibrary_{}\")\n"
                       "}}\n\n",
                       anims_[i]->res_file_name, anims_[i]->res_file_name);
        }
    }

    out_.flush();
}

}  // namespace r2ga
